---
# light automations

- alias: WakeUp Light Bedroom
  id: '1500581870'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == states('sensor.wakeup_start_time_lights') }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup
        state: 'on'
      - condition: state
        entity_id: !secret person_1
        state: home
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekends
            state: 'on'
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
  action:
    - service: adaptive_lighting.set_manual_control
      data:
        entity_id: switch.adaptive_lighting_main_lights
        lights: light.deckenspots
        manual_control: true
    - service: light.turn_on
      data:
        entity_id: light.deckenspots
        brightness: 2
        color_temp: 497
    - delay:
        seconds: 1
    - service: light.turn_on
      data_template:
        entity_id: light.deckenspots
        brightness: "{{ states('input_number.wakeup_target_brightness') | int }}"
        transition: "{{ states('input_number.wakeup_duration') | multiply(60) | int }}"
    - delay: "{{ states('input_number.wakeup_duration') | multiply(120) | int }}"
    - service: adaptive_lighting.set_manual_control
      data:
        entity_id: switch.adaptive_lighting_main_lights
        lights: light.deckenspots
        manual_control: false

- alias: Random light - Deckenspots
  id: '1500581871'
  trigger:
    - platform: time_pattern
      minutes: /2
      seconds: 0
    - platform: state
      entity_id: input_boolean.loop_livingcolors_1
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.loop_livingcolors_1
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.deckenspots
    data_template:
      # entity_id: light.deckenspots
      # effect: random
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
      transition: 5
      brightness: 255

- alias: Random light - Stehlampe
  id: '1500581872'
  trigger:
    - platform: time_pattern
      minutes: /2
      seconds: 0
    - platform: state
      entity_id: input_boolean.loop_livingcolors_2
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.loop_livingcolors_2
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.stehlampe
    data_template:
      # entity_id: light.stehlampe
      # effect: random
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
      transition: 5
      brightness: 132

- id: '1555301143'
  alias: Turn off loop-effect
  trigger:
    - platform: state
      entity_id: light.stehlampe
      to: 'off'
    - platform: state
      entity_id: light.deckenspots
      to: 'off'
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'light.stehlampe' -%}
            input_boolean.loop_livingcolors_2
          {% elif trigger.entity_id == 'light.deckenspots' -%}
            input_boolean.loop_livingcolors_1
          {% endif %}

- id: '1555301145'
  alias: Gaming PS4
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      to: playing
  condition:
    - condition: time
      after: '19:00:00'
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: !secret person_1
      state: home
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.loop_livingcolors_2
    - service: light.turn_off
      data:
        entity_id: light.deckenleuchte

- id: '1555301146'
  alias: Stop playing PS4
  trigger:
    - platform: state
      entity_id: media_player.playstation_4
      from: playing
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: !secret person_1
      state: home
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.deckenleuchte_grp_nightlight

- id: '1519077406'
  alias: Ready for bed
  trigger:
    at: '21:30:00'
    platform: time
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: !secret person_1
      state: home
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.deckenleuchte_grp_nightlight

- id: '1609948156898'
  alias: Motion-activated toilet light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '180'
      motion_entity: binary_sensor.motion_sensor
      light_target:
        entity_id: light.light_8

- id: '1609948156902'
  alias: Motion-activated bathroom light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '300'
      motion_entity: binary_sensor.motion_sensor_2
      light_target:
        entity_id: light.light_7

- id: '1609948156899'
  alias: turn toilet lights off
  description: ''
  use_blueprint:
    path: knapoc/light_off_time.yaml
    input:
      on_time: '600'
      light_entity: light.light_8

- id: '1609948156900'
  alias: turn bathroom lights off
  description: ''
  use_blueprint:
    path: knapoc/light_off_time.yaml
    input:
      on_time: '2700'
      light_entity: light.light_7

- id: '1609948156901'
  alias: turn hall lights off
  description: ''
  use_blueprint:
    path: knapoc/light_off_time.yaml
    input:
      on_time: '2700'
      light_entity: light.light_9

- id: '1609056340356'
  alias: Mi Magic Cube
  description: ''
  use_blueprint:
    path: bergstrom/mi-magic-cube-deconz-45-actions.yaml
    input:
      remote: a0b7f469e80183add666c9a85c9c1084
      cube_shake:
        - type: toggle
          device_id: f9c4b764194911eb9b57a98c1840daa3
          entity_id: light.nachttischlampe
          domain: light
      rotate_clockwise:
        - type: brightness_increase
          device_id: f9c4b764194911eb9b57a98c1840daa3
          entity_id: light.nachttischlampe
          domain: light
      rotate_counter_clockwise:
        - type: brightness_decrease
          device_id: f9c4b764194911eb9b57a98c1840daa3
          entity_id: light.nachttischlampe
          domain: light
      one_to_one:
        - type: toggle
          device_id: c415d227da5448fc83453f4441dde0c7
          entity_id: light.deckenspots
          domain: light

- id: '1614239882832'
  alias: Tag nightstandlamp is scanned
  trigger:
    - platform: tag
      tag_id: 2809481d-ade3-4905-afcd-787291190fb2
  action:
    - type: toggle
      device_id: f9c4b764194911eb9b57a98c1840daa3
      entity_id: light.nachttischlampe
      domain: light
  mode: single
