---
# vacuum automations

- id: '1555971390'
  alias: roborock auto turn on
  trigger:
    - platform: time_pattern
      minutes: '/15'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: counter.vacuum_dustbin
        below: 7
      - condition: numeric_state
        entity_id: counter.vacuum_runs_per_day
        below: 1
      - condition: state
        entity_id: binary_sensor.is_home
        state: 'off'
        for:
          minutes: 20
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.vacuum_weekends
            state: 'on'
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
      - condition: template
        value_template: "{{ state_attr('vacuum.roborock', 'battery_level') == 100 }}"
      - condition: template
        value_template: "{{ states('sensor.time') >= states('input_datetime.vacuum_schedule_1_from') }}"
      - condition: template
        value_template: "{{ states('sensor.time') <= states('input_datetime.vacuum_schedule_1_to') }}"
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.roborock

- id: '1555971391'
  alias: roborock clean counter
  trigger:
    - platform: state
      entity_id: vacuum.roborock
      from: 'docked'
      to: 'cleaning'
  action:
    - service: counter.increment
      data:
        entity_id: counter.vacuum_dustbin
    - service: counter.increment
      data:
        entity_id: counter.vacuum_runs_per_day

- id: '1555975479'
  alias: roborock clean notification
  trigger:
    - platform: time_pattern
      hours: '/2'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret person_1
        state: 'home'
        for:
          minutes: 20
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
      - condition: numeric_state
        entity_id: counter.vacuum_dustbin
        above: 4
      - condition: template
        value_template: "{{ states('vacuum.roborock') != 'cleaning' }}"
  action:
    - service: !secret notify_ios
      data_template:
        message: "Staubsauger ist zu entleeren. Anzahl der Saugvorgänge: {{ states('counter.vacuum_dustbin') }}"
        data:
          push:
            category: emptyroborock

- alias: roborock maintenance notification
  id: '1610223727000'
  trigger:
    - platform: numeric_state
      entity_id: sensor.roborock_main_brush
      below: 1
    - platform: numeric_state
      entity_id: sensor.roborock_right_side_brush
      below: 1
    - platform: numeric_state
      entity_id: sensor.roborock_main_filter
      below: 1
    - platform: numeric_state
      entity_id: sensor.roborock_main_sensor
      below: 1
  action:
    - service: !secret notify_ios
      data_template:
        message: >
          Vacuum has to be maintained.
          {% if states('sensor.roborock_main_brush') | int <= 1 %}
            Main brush: {{ states('sensor.roborock_main_brush_hours') }}h left.
          {% endif %}
          {% if states('sensor.roborock_right_side_brush') | int <= 1 %}
            Side brush: {{ states('sensor.roborock_right_side_brush_hours') }}h left.
          {% endif %}
          {% if states('sensor.roborock_main_filter') | int <= 1 %}
            Filter: {{ states('sensor.roborock_main_filter_hours') }}h left.
          {% endif %}
          {% if states('sensor.roborock_sensor') | int <= 1 %}
            Sensor: {{ states('sensor.roborock_sensor_hours') }}h left.
          {% endif %}

- alias: roborock cleaned
  id: '1555975480'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: EMPTY_ROBOROCK_NOW
    - platform: event
      event_type: deconz_event
      event_data:
        unique_id: 00:15:8d:00:04:23:f2:45
        event: 1002
  condition:
    condition: state
    entity_id: !secret person_1
    state: 'home'
  action:
    - service: mqtt.publish
      data:
        topic: valetudo/roborock/GoToLocationCapability/go/set
        payload: "37b097a4-c502-47a9-b025-594255d4eb27"
    - wait_template: "{{ is_state('vacuum.roborock', 'returning') }}"
    - service: counter.reset
      data:
        entity_id: counter.vacuum_dustbin
    - service: counter.decrement
      data:
        entity_id: counter.vacuum_runs_per_day

- alias: roborock reset runs per day
  id: '1596000980'
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: counter.reset
      data:
        entity_id: counter.vacuum_runs_per_day

- alias: New Valetudo SW Version
  id: '1597738993'
  mode: single
  trigger:
    - platform: template
      value_template: "{{ states('sensor.latest_valetudo') != states('sensor.version_valetudo') }}"
  action:
    - service: persistent_notification.create
      data:
        message: '{{ states(''sensor.latest_valetudo'') }}'
        title: Valetudo upgrade pending
